<?php

namespace App\DataFixtures;

use App\Entity\Professional;
use App\Entity\Review;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class AppFixtures extends Fixture
{
    private array $pros = [

        // ── PARIS (75) ── 6 professionnels ─────────────────────────────────

        [
            'nomSociete' => 'Boucherie El Amine',
            'nomResponsable' => 'Benmansour',
            'prenomResponsable' => 'Mohamed',
            'genre' => 'M',
            'domaineActivite' => 'Alimentation',
            'profession' => 'Boucher halal artisan',
            'siret' => '41234567800014',
            'adresseRue' => '18 rue du Faubourg Saint-Denis',
            'codePostal' => '75010',
            'ville' => 'Paris',
            'latitude' => 48.8720,
            'longitude' => 2.3590,
            'telephone' => '0142001001',
            'email' => 'm.benmansour@boucherie-elamine.fr',
            'description' => 'Boucherie halal artisanale depuis 2005. Viandes fraîches sélectionnées auprès d\'éleveurs certifiés : agneau, bœuf, veau, poulet. Découpe sur mesure, livraison disponible. Accueil chaleureux du lundi au samedi.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.9,
            'totalAvis' => 6,
        ],
        [
            'nomSociete' => 'Cabinet Dr Hadj Amar',
            'nomResponsable' => 'Hadj Amar',
            'prenomResponsable' => 'Karim',
            'genre' => 'M',
            'domaineActivite' => 'Santé',
            'profession' => 'Médecin généraliste',
            'siret' => '42345678900014',
            'adresseRue' => '45 boulevard de Strasbourg',
            'codePostal' => '75010',
            'ville' => 'Paris',
            'latitude' => 48.8747,
            'longitude' => 2.3561,
            'telephone' => '0142001002',
            'email' => 'k.hadjamar@cabinet-paris10.fr',
            'description' => 'Médecin généraliste, secteur 1. Consultations sur rendez-vous et en urgence. Suivi médical complet, certificats, renouvellements d\'ordonnances. Parle arabe et français. Accès PMR.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.7,
            'totalAvis' => 5,
        ],
        [
            'nomSociete' => 'Maître Benali & Associés',
            'nomResponsable' => 'Benali',
            'prenomResponsable' => 'Sara',
            'genre' => 'F',
            'domaineActivite' => 'Droit & Conseil',
            'profession' => 'Avocate au Barreau de Paris',
            'siret' => '43456789000014',
            'adresseRue' => '12 rue de la Paix',
            'codePostal' => '75002',
            'ville' => 'Paris',
            'latitude' => 48.8689,
            'longitude' => 2.3311,
            'telephone' => '0142001003',
            'email' => 's.benali@cabinet-benali.fr',
            'description' => 'Cabinet d\'avocats spécialisé en droit de la famille, droit des affaires et droit des étrangers. Consultations en français et arabe. Honoraires transparents. Engagement total pour la défense de vos droits.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.8,
            'totalAvis' => 4,
        ],
        [
            'nomSociete' => 'Pharmacie de Belleville',
            'nomResponsable' => 'Naciri',
            'prenomResponsable' => 'Youcef',
            'genre' => 'M',
            'domaineActivite' => 'Santé',
            'profession' => 'Pharmacien titulaire',
            'siret' => '44567890100014',
            'adresseRue' => '2 rue de Belleville',
            'codePostal' => '75020',
            'ville' => 'Paris',
            'latitude' => 48.8720,
            'longitude' => 2.3847,
            'telephone' => '0142001004',
            'email' => 'y.naciri@pharmacie-belleville.fr',
            'description' => 'Pharmacie de quartier ouverte 7j/7. Délivrance d\'ordonnances, conseils santé, préparations magistrales, matériel médical et parapharmacie. Équipe bilingue français-arabe à votre service.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.6,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Électricité Zitouni Bâtiment',
            'nomResponsable' => 'Zitouni',
            'prenomResponsable' => 'Mourad',
            'genre' => 'M',
            'domaineActivite' => 'Bâtiment & Travaux',
            'profession' => 'Électricien certifié RGE',
            'siret' => '45678901200014',
            'adresseRue' => '8 rue d\'Alésia',
            'codePostal' => '75014',
            'ville' => 'Paris',
            'latitude' => 48.8282,
            'longitude' => 2.3262,
            'telephone' => '0142001005',
            'email' => 'm.zitouni@electricite-zitouni.fr',
            'description' => 'Électricien certifié RGE Qualifelec. Installation, mise aux normes, dépannage, tableau électrique, VMC, domotique. Devis gratuit sous 24h. Travaux propres et soignés en Île-de-France.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.5,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Le Souk Parisien',
            'nomResponsable' => 'Rahmani',
            'prenomResponsable' => 'Nadia',
            'genre' => 'F',
            'domaineActivite' => 'Alimentation',
            'profession' => 'Restauratrice traiteur',
            'siret' => '46789012300014',
            'adresseRue' => '33 rue des Rosiers',
            'codePostal' => '75004',
            'ville' => 'Paris',
            'latitude' => 48.8553,
            'longitude' => 2.3534,
            'telephone' => '0142001006',
            'email' => 'n.rahmani@lesoukparisien.fr',
            'description' => 'Restaurant et traiteur orientale au cœur du Marais. Couscous, tagines, pastillas, pâtisseries maison. Formule déjeuner et service traiteur pour réceptions et événements familiaux. Tout halal.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.8,
            'totalAvis' => 5,
        ],

        // ── LYON (69) ── 5 professionnels ──────────────────────────────────

        [
            'nomSociete' => 'Boucherie Halal du Rhône',
            'nomResponsable' => 'Chafik',
            'prenomResponsable' => 'Hassan',
            'genre' => 'M',
            'domaineActivite' => 'Alimentation',
            'profession' => 'Boucher halal artisan',
            'siret' => '47890123400014',
            'adresseRue' => '14 rue Moncey',
            'codePostal' => '69003',
            'ville' => 'Lyon',
            'latitude' => 45.7569,
            'longitude' => 4.8410,
            'telephone' => '0472002001',
            'email' => 'h.chafik@boucherie-rhone.fr',
            'description' => 'Boucherie halal certifiée, ouverte depuis 2009. Viandes de qualité supérieure : agneau du Limousin, bœuf charolais, volaille Label Rouge. Découpes à la demande, marinades maison.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.9,
            'totalAvis' => 4,
        ],
        [
            'nomSociete' => 'Cabinet Pédiatrique Dr Amara',
            'nomResponsable' => 'Amara',
            'prenomResponsable' => 'Fatima',
            'genre' => 'F',
            'domaineActivite' => 'Santé',
            'profession' => 'Pédiatre',
            'siret' => '48901234500014',
            'adresseRue' => '28 cours Gambetta',
            'codePostal' => '69007',
            'ville' => 'Lyon',
            'latitude' => 45.7451,
            'longitude' => 4.8500,
            'telephone' => '0472002002',
            'email' => 'f.amara@pediatrie-lyon.fr',
            'description' => 'Pédiatre libérale, secteur 2. Suivi de l\'enfant de la naissance à l\'adolescence. Vaccinations, bilans de santé, urgences pédiatriques. Consultations en français, arabe et berbère.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.8,
            'totalAvis' => 4,
        ],
        [
            'nomSociete' => 'Agence Confluence Immobilier',
            'nomResponsable' => 'Belahouel',
            'prenomResponsable' => 'Riad',
            'genre' => 'M',
            'domaineActivite' => 'Immobilier',
            'profession' => 'Agent immobilier',
            'siret' => '49012345600014',
            'adresseRue' => '3 rue de la Confluence',
            'codePostal' => '69002',
            'ville' => 'Lyon',
            'latitude' => 45.7407,
            'longitude' => 4.8168,
            'telephone' => '0472002003',
            'email' => 'r.belahouel@confluence-immo.fr',
            'description' => 'Agence immobilière indépendante spécialisée achat, vente et gestion locative dans la métropole lyonnaise. Estimation gratuite, mandat exclusif ou simple. Accompagnement jusqu\'à la signature.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.5,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Génie Électrique Kamal',
            'nomResponsable' => 'Kamal',
            'prenomResponsable' => 'Yassine',
            'genre' => 'M',
            'domaineActivite' => 'Bâtiment & Travaux',
            'profession' => 'Électricien RGE',
            'siret' => '50123456700014',
            'adresseRue' => '55 avenue Jean Jaurès',
            'codePostal' => '69007',
            'ville' => 'Lyon',
            'latitude' => 45.7472,
            'longitude' => 4.8413,
            'telephone' => '0472002004',
            'email' => 'y.kamal@genie-electrique-kamal.fr',
            'description' => 'Électricien qualifié RGE. Installation complète, rénovation électrique, borne de recharge véhicule électrique, alarme et sécurité. Intervention sur Lyon et sa banlieue. Devis gratuit.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.4,
            'totalAvis' => 2,
        ],
        [
            'nomSociete' => 'Académie Lumière Soutien Scolaire',
            'nomResponsable' => 'Ouled',
            'prenomResponsable' => 'Siham',
            'genre' => 'F',
            'domaineActivite' => 'Éducation & Formation',
            'profession' => 'Enseignante & tutrice certifiée',
            'siret' => '51234567800014',
            'adresseRue' => '7 cours de la Liberté',
            'codePostal' => '69003',
            'ville' => 'Lyon',
            'latitude' => 45.7572,
            'longitude' => 4.8497,
            'telephone' => '0472002005',
            'email' => 's.ouled@academie-lumiere.fr',
            'description' => 'Soutien scolaire toutes matières du primaire à la terminale. Professeure certifiée en mathématiques et physique. Cours individuels ou en petits groupes, préparation au bac. Résultats garantis.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.7,
            'totalAvis' => 3,
        ],

        // ── MARSEILLE (13) ── 5 professionnels ─────────────────────────────

        [
            'nomSociete' => 'Boucherie du Soleil',
            'nomResponsable' => 'Bensaid',
            'prenomResponsable' => 'Rachid',
            'genre' => 'M',
            'domaineActivite' => 'Alimentation',
            'profession' => 'Boucher halal artisan',
            'siret' => '52345678900014',
            'adresseRue' => '65 boulevard de la Libération',
            'codePostal' => '13001',
            'ville' => 'Marseille',
            'latitude' => 43.2963,
            'longitude' => 5.3836,
            'telephone' => '0491003001',
            'email' => 'r.bensaid@boucherie-soleil.fr',
            'description' => 'Boucherie halal artisanale fondée en 2001. Spécialités : méchoui entier sur commande, merguez maison, kefta fraîche. Approvisionnement direct auprès d\'éleveurs provençaux. Ouvert 6j/7.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.9,
            'totalAvis' => 5,
        ],
        [
            'nomSociete' => 'Cabinet Dentaire Dr Zerrouk',
            'nomResponsable' => 'Zerrouk',
            'prenomResponsable' => 'Samir',
            'genre' => 'M',
            'domaineActivite' => 'Santé',
            'profession' => 'Chirurgien-dentiste',
            'siret' => '53456789000014',
            'adresseRue' => '18 rue Paradis',
            'codePostal' => '13006',
            'ville' => 'Marseille',
            'latitude' => 43.2886,
            'longitude' => 5.3789,
            'telephone' => '0491003002',
            'email' => 's.zerrouk@dentiste-marseille.fr',
            'description' => 'Cabinet dentaire moderne équipé en numérique. Soins conservateurs, prothèses, implants, esthétique dentaire. Conventionné secteur 2. Urgences acceptées. Parle arabe, français, espagnol.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.7,
            'totalAvis' => 4,
        ],
        [
            'nomSociete' => 'Rénovation Mediterra Bouzid',
            'nomResponsable' => 'Bouzid',
            'prenomResponsable' => 'Omar',
            'genre' => 'M',
            'domaineActivite' => 'Bâtiment & Travaux',
            'profession' => 'Carreleur & entrepreneur rénovation',
            'siret' => '54567890100014',
            'adresseRue' => '43 boulevard Michelet',
            'codePostal' => '13009',
            'ville' => 'Marseille',
            'latitude' => 43.2636,
            'longitude' => 5.3919,
            'telephone' => '0491003003',
            'email' => 'o.bouzid@renovation-mediterra.fr',
            'description' => 'Artisan carreleur spécialisé salle de bain, cuisine et terrasse. Pose de carrelage grand format, mosaïque, zellige. Rénovation complète intérieure. Devis gratuit, finitions impeccables.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.6,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Traiteur Orient Plus',
            'nomResponsable' => 'Hamza',
            'prenomResponsable' => 'Leila',
            'genre' => 'F',
            'domaineActivite' => 'Alimentation',
            'profession' => 'Traiteur événementiel',
            'siret' => '55678901200014',
            'adresseRue' => '12 avenue du Prado',
            'codePostal' => '13006',
            'ville' => 'Marseille',
            'latitude' => 43.2767,
            'longitude' => 5.3827,
            'telephone' => '0491003004',
            'email' => 'l.hamza@traiteur-orientplus.fr',
            'description' => 'Service traiteur halal pour mariages, baptêmes, fiançailles et réceptions d\'entreprise. Menu oriental ou mixte. Cuisine faite maison, présentation soignée. De 20 à 500 convives.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.8,
            'totalAvis' => 4,
        ],
        [
            'nomSociete' => 'Auto École Conduite Marseille',
            'nomResponsable' => 'Terki',
            'prenomResponsable' => 'Bilal',
            'genre' => 'M',
            'domaineActivite' => 'Éducation & Formation',
            'profession' => 'Moniteur auto-école agréé',
            'siret' => '56789012300014',
            'adresseRue' => '7 place de la Joliette',
            'codePostal' => '13002',
            'ville' => 'Marseille',
            'latitude' => 43.3044,
            'longitude' => 5.3645,
            'telephone' => '0491003005',
            'email' => 'b.terki@autoecole-conduite13.fr',
            'description' => 'Auto-école agréée code de la route et conduite accompagnée. Formule boîte manuelle et automatique. Permis B, AAC, conduite sur autoroute. Moniteurs patient et pédagogue. Tarifs compétitifs.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.5,
            'totalAvis' => 2,
        ],

        // ── TOULOUSE (31) ── 5 professionnels ──────────────────────────────

        [
            'nomSociete' => 'Pharmacie Abdelkader',
            'nomResponsable' => 'Abdelkader',
            'prenomResponsable' => 'Amine',
            'genre' => 'M',
            'domaineActivite' => 'Santé',
            'profession' => 'Pharmacien titulaire',
            'siret' => '57890123400014',
            'adresseRue' => '40 allée Jean Jaurès',
            'codePostal' => '31000',
            'ville' => 'Toulouse',
            'latitude' => 43.6082,
            'longitude' => 1.4507,
            'telephone' => '0561004001',
            'email' => 'a.abdelkader@pharmacie31.fr',
            'description' => 'Pharmacie de quartier ouverte du lundi au samedi. Délivrance d\'ordonnances, conseils en phytothérapie et médecine naturelle, parapharmacie bio, orthopédie. Équipe accueillante et disponible.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.6,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Cabinet Maître Ouali',
            'nomResponsable' => 'Ouali',
            'prenomResponsable' => 'Malika',
            'genre' => 'F',
            'domaineActivite' => 'Droit & Conseil',
            'profession' => 'Avocate en droit des affaires',
            'siret' => '58901234500014',
            'adresseRue' => '5 place du Capitole',
            'codePostal' => '31000',
            'ville' => 'Toulouse',
            'latitude' => 43.6047,
            'longitude' => 1.4431,
            'telephone' => '0561004002',
            'email' => 'm.ouali@avocat-capitole.fr',
            'description' => 'Avocate inscrite au Barreau de Toulouse. Droit des affaires, création d\'entreprise, baux commerciaux, recouvrement de créances, droit du travail. Consultation en ligne ou en cabinet.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.7,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Aziz Rénovation & Maçonnerie',
            'nomResponsable' => 'Aziz',
            'prenomResponsable' => 'Mohamed',
            'genre' => 'M',
            'domaineActivite' => 'Bâtiment & Travaux',
            'profession' => 'Maçon entrepreneur général',
            'siret' => '59012345600014',
            'adresseRue' => '22 route de Bayonne',
            'codePostal' => '31300',
            'ville' => 'Toulouse',
            'latitude' => 43.5857,
            'longitude' => 1.4147,
            'telephone' => '0561004003',
            'email' => 'm.aziz@aziz-renovation.fr',
            'description' => 'Entreprise de maçonnerie et rénovation générale. Ravalement de façade, extension, surélévation, gros œuvre. Certifié Qualibat. Devis gratuit et détaillé. Chantiers propres, délais respectés.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.4,
            'totalAvis' => 2,
        ],
        [
            'nomSociete' => 'Salon Coiffure Nadia Style',
            'nomResponsable' => 'Ramdani',
            'prenomResponsable' => 'Nadia',
            'genre' => 'F',
            'domaineActivite' => 'Beauté & Bien-être',
            'profession' => 'Coiffeuse styliste',
            'siret' => '60123456700014',
            'adresseRue' => '14 rue Bayard',
            'codePostal' => '31000',
            'ville' => 'Toulouse',
            'latitude' => 43.6052,
            'longitude' => 1.4528,
            'telephone' => '0561004004',
            'email' => 'n.ramdani@nadia-style.fr',
            'description' => 'Salon de coiffure spécialisé cheveux bouclés, frisés et crépus. Coupe, brushing, balayage, lissage kératine, soins capillaires naturels. Ambiance féminine et bienveillante. Sur rendez-vous.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.8,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Plomberie Chauffage Haddad',
            'nomResponsable' => 'Haddad',
            'prenomResponsable' => 'Sofiane',
            'genre' => 'M',
            'domaineActivite' => 'Bâtiment & Travaux',
            'profession' => 'Plombier chauffagiste RGE',
            'siret' => '61234567800014',
            'adresseRue' => '8 avenue de la Gloire',
            'codePostal' => '31500',
            'ville' => 'Toulouse',
            'latitude' => 43.5956,
            'longitude' => 1.4741,
            'telephone' => '0561004005',
            'email' => 's.haddad@plomberie-haddad.fr',
            'description' => 'Plombier chauffagiste certifié RGE. Dépannage urgent 7j/7, installation chaudière gaz ou pompe à chaleur, chauffe-eau thermodynamique, radiateurs. Diagnostic gratuit sur Toulouse et alentours.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.5,
            'totalAvis' => 2,
        ],

        // ── BOUTIQUES EN LIGNE (e-commerce) ────────────────────────────────

        [
            'type' => Professional::TYPE_ECOMMERCE,
            'nomSociete' => 'Épicerie Baraka Shop',
            'domaineActivite' => 'Alimentation & Épicerie',
            'email' => 'contact@baraka-shop.fr',
            'siteEcommerce' => 'https://baraka-shop.fr',
            'description' => 'Épicerie orientale en ligne. Épices, légumineuses, conserves, dattes, huiles d\'argan et produits du terroir maghrébin livrés à domicile en 48h partout en France.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.7,
            'totalAvis' => 3,
        ],
        [
            'type' => Professional::TYPE_ECOMMERCE,
            'nomSociete' => 'Robes Élégance Orientale',
            'domaineActivite' => 'Vêtements & Mode',
            'email' => 'contact@robes-elegance.fr',
            'siteEcommerce' => 'https://robes-elegance.fr',
            'description' => 'Boutique en ligne spécialisée en robes de soirée orientales, caftans et abayas de créateurs. Collections exclusives pour mariages, fiançailles et fêtes. Livraison France et international.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.5,
            'totalAvis' => 2,
        ],
        [
            'type' => Professional::TYPE_ECOMMERCE,
            'nomSociete' => 'Cosmétiques Naturels Safran',
            'domaineActivite' => 'Beauté & Cosmétiques',
            'email' => 'bonjour@cosmetiques-safran.fr',
            'siteEcommerce' => 'https://cosmetiques-safran.fr',
            'description' => 'Soins naturels et halal : huile d\'argan pure, savon beldi, rhassoul, henné naturel, eau de rose. Formules artisanales sans parabènes ni sulfates. Certifié cruelty-free.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.8,
            'totalAvis' => 4,
        ],

        // ── LILLE (59) ── 5 professionnels ─────────────────────────────────

        [
            'nomSociete' => 'Boucherie Chez Nordine',
            'nomResponsable' => 'Khelifi',
            'prenomResponsable' => 'Nordine',
            'genre' => 'M',
            'domaineActivite' => 'Alimentation',
            'profession' => 'Boucher halal',
            'siret' => '62345678900014',
            'adresseRue' => '84 rue Gambetta',
            'codePostal' => '59000',
            'ville' => 'Lille',
            'latitude' => 50.6292,
            'longitude' => 3.0600,
            'telephone' => '0320005001',
            'email' => 'n.khelifi@boucherie-nordine.fr',
            'description' => 'Boucherie halal traditionnelle, institution du quartier depuis 18 ans. Viandes fraîches du jour, agneau entier sur commande, chorba et merguez maison. Accueil familial et prix juste.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.9,
            'totalAvis' => 4,
        ],
        [
            'nomSociete' => 'Cabinet Comptable Atlas',
            'nomResponsable' => 'Atmani',
            'prenomResponsable' => 'Driss',
            'genre' => 'M',
            'domaineActivite' => 'Finance & Assurance',
            'profession' => 'Expert-comptable',
            'siret' => '63456789000014',
            'adresseRue' => '20 rue du Molinel',
            'codePostal' => '59800',
            'ville' => 'Lille',
            'latitude' => 50.6300,
            'longitude' => 3.0590,
            'telephone' => '0320005002',
            'email' => 'd.atmani@cabinet-atlas.fr',
            'description' => 'Cabinet d\'expertise comptable pour TPE, PME et auto-entrepreneurs. Comptabilité, bilan, liasse fiscale, paie, création d\'entreprise. Accompagnement personnalisé et réactif. Premier rendez-vous offert.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.6,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Menuiserie Bouaziz Bois & Création',
            'nomResponsable' => 'Bouaziz',
            'prenomResponsable' => 'Mehdi',
            'genre' => 'M',
            'domaineActivite' => 'Bâtiment & Travaux',
            'profession' => 'Menuisier poseur',
            'siret' => '64567890100014',
            'adresseRue' => '15 rue d\'Arras',
            'codePostal' => '59000',
            'ville' => 'Lille',
            'latitude' => 50.6261,
            'longitude' => 3.0575,
            'telephone' => '0320005003',
            'email' => 'm.bouaziz@menuiserie-bouaziz.fr',
            'description' => 'Menuisier artisan spécialisé en pose de parquet, fenêtres PVC et aluminium, portes intérieures, dressings et placards sur mesure. Travail soigné, matériaux certifiés. Devis sans engagement.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.5,
            'totalAvis' => 2,
        ],
        [
            'nomSociete' => 'Institut Le Jasmin',
            'nomResponsable' => 'Belhaj',
            'prenomResponsable' => 'Samira',
            'genre' => 'F',
            'domaineActivite' => 'Beauté & Bien-être',
            'profession' => 'Esthéticienne cosméticienne',
            'siret' => '65678901200014',
            'adresseRue' => '6 place du Général de Gaulle',
            'codePostal' => '59800',
            'ville' => 'Lille',
            'latitude' => 50.6380,
            'longitude' => 3.0636,
            'telephone' => '0320005004',
            'email' => 's.belhaj@institut-lejasmin.fr',
            'description' => 'Institut de beauté pour femmes. Épilation à la cire et au fil, soins du visage, maquillage (mariages et événements), onglerie, sourcils. Produits naturels et halal. Ambiance féminine et intime.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.8,
            'totalAvis' => 3,
        ],
        [
            'nomSociete' => 'Transport & Déménagement Saad',
            'nomResponsable' => 'Saad',
            'prenomResponsable' => 'Hamid',
            'genre' => 'M',
            'domaineActivite' => 'Autre',
            'profession' => 'Déménageur transporteur',
            'siret' => '66789012300014',
            'adresseRue' => '30 boulevard de Belfort',
            'codePostal' => '59000',
            'ville' => 'Lille',
            'latitude' => 50.6185,
            'longitude' => 3.0568,
            'telephone' => '0320005005',
            'email' => 'h.saad@transport-saad.fr',
            'description' => 'Déménageur professionnel et transporteur de marchandises. Devis gratuit sous 2h. Camion 20m³ avec monte-meuble. Emballage, protection et assurance inclus. Disponible week-ends et jours fériés.',
            'statut' => Professional::STATUT_ACTIF,
            'starsAverage' => 4.4,
            'totalAvis' => 2,
        ],
    ];

    private array $reviewsData = [
        // Boucherie El Amine (0)
        [0, 'Ahmed K.',    5, 'Meilleure boucherie du 10ème ! Les viandes sont toujours fraîches et la découpe est parfaite. Mohamed est un vrai artisan.'],
        [0, 'Fatou S.',    5, 'Accueil super sympa, produits de qualité. Les merguez maison sont incroyables. Je reviendrai chaque semaine.'],
        [0, 'Moussa T.',   5, 'J\'ai commandé un agneau entier pour l\'Aïd, service impeccable et livraison à l\'heure. Bravo !'],
        [0, 'Claire B.',   5, 'Boucher sérieux et passionné. Il explique bien la provenance des viandes, ça donne confiance.'],
        [0, 'Hamza L.',    5, 'Depuis que j\'ai découvert cette boucherie, je ne vais nulle part ailleurs. Rapport qualité-prix imbattable.'],
        [0, 'Karim M.',    4, 'Très bon boucher, parfois un peu d\'attente le samedi mais ça vaut le coup pour la qualité.'],
        // Dr Hadj Amar (1)
        [1, 'Marie L.',    5, 'Médecin à l\'écoute et très humain. Il prend le temps d\'expliquer chaque chose. Je recommande vivement.'],
        [1, 'Rachid B.',   5, 'Excellent praticien, ponctuel et efficace. Parle arabe ce qui est un vrai plus pour ma mère.'],
        [1, 'Isabelle M.', 4, 'Médecin sérieux, parfois un peu d\'attente mais le suivi est vraiment bon.'],
        [1, 'Tariq O.',    5, 'Mon médecin de famille depuis 5 ans. Toujours disponible et jamais de jugement. Merci docteur !'],
        [1, 'Leila F.',    5, 'Cabinet propre, accueil agréable. Le docteur est compétent et bienveillant.'],
        // Maître Benali (2)
        [2, 'Nicolas P.',  5, 'Maître Benali a géré mon litige commercial avec beaucoup de compétence. Résultat excellent en peu de temps.'],
        [2, 'Sara D.',     4, 'Avocate sérieuse et réactive. Elle répond aux emails rapidement et explique clairement les démarches.'],
        [2, 'Kamel H.',    5, 'Accompagnement parfait pour la création de ma SARL. Très professionnel et tarifs honnêtes.'],
        [2, 'Pauline V.',  5, 'Je la recommande sans hésiter. Elle défend vraiment ses clients avec conviction.'],
        // Boucherie du Soleil Marseille (11)
        [11, 'Fatou D.',   5, 'La meilleure boucherie halal de Marseille ! Viandes toujours fraîches et Rachid est adorable.'],
        [11, 'Jean-P. M.', 5, 'Méchoui commandé pour 50 personnes, tout était parfait. Ponctuel et délicieux.'],
        [11, 'Amina K.',   5, 'Des années de fidélité et ça ne change pas. Qualité constante et prix correct.'],
        [11, 'Pierre D.',  4, 'Très bonne boucherie, merguez maison excellentes. Parfois fermé plus tôt que prévu.'],
        [11, 'Zineb R.',   5, 'Service impeccable. Rachid connaît son métier et ça se voit dans chaque produit.'],
        // Dr Zerrouk Marseille (12)
        [12, 'Hana B.',    5, 'Dentiste très doux et professionnel. J\'avais peur et il m\'a mise à l\'aise immédiatement.'],
        [12, 'Omar T.',    5, 'Cabinet moderne, pas de douleur pendant les soins. Je recommande à toute la famille.'],
        [12, 'Sophie M.',  4, 'Bon dentiste, explique bien les soins. Rendez-vous pas toujours facile à avoir mais ça vaut l\'attente.'],
        [12, 'Yassir K.',  5, 'Implant réalisé parfaitement. Suivi post-opératoire exemplaire. Merci docteur Zerrouk !'],
        // Le Souk Parisien (5)
        [5, 'Thomas B.',   5, 'Couscous exceptionnel, exactement comme chez ma grand-mère. Service rapide et chaleureux.'],
        [5, 'Lucie V.',    5, 'Traiteur pour mon mariage, 120 convives. Tout était parfait : présentation, goût, ponctualité.'],
        [5, 'Mehdi A.',    5, 'La pastilla au poulet est à tomber. Je commande régulièrement pour mes réceptions.'],
        [5, 'Julie P.',    4, 'Très bon restaurant, portions généreuses. L\'attente peut être longue le vendredi soir.'],
        [5, 'Karim S.',    5, 'Nadia est une vraie cuisinière. On sent la passion dans chaque plat.'],
        // Traiteur Orient Plus Marseille (14)
        [14, 'Soraya B.',  5, 'Traiteur pour le mariage de ma fille. 200 personnes régalées ! Je les recommande les yeux fermés.'],
        [14, 'Hamid K.',   5, 'Service professionnel du début à la fin. Les gâteaux orientaux étaient sublimes.'],
        [14, 'Isabelle R.',5, 'Excellente prestation pour notre soirée d\'entreprise. Cuisine raffinée et service impeccable.'],
        [14, 'Youssef A.', 5, 'Leila sait créer une ambiance unique. Tout le monde a adoré lors de notre baptême.'],
        // Boucherie Chez Nordine Lille (21)
        [21, 'Rachid L.',  5, 'Nordine est un vrai professionnel. Viandes de première qualité et prix honnêtes.'],
        [21, 'Sarah M.',   5, 'La chorba maison est exceptionnelle ! Je viens toute la semaine tellement c\'est bon.'],
        [21, 'Omar H.',    5, 'Boucherie de confiance depuis des années. Jamais déçu, toujours souriant.'],
        [21, 'Amira K.',   4, 'Très bon boucher, petite attente parfois le samedi mais les produits valent le détour.'],
    ];

    public function load(ObjectManager $manager): void
    {
        $professionalRefs = [];

        foreach ($this->pros as $index => $data) {
            $pro = new Professional();
            $type = $data['type'] ?? Professional::TYPE_PHYSIQUE;
            $pro->setType($type);
            $pro->setNomSociete($data['nomSociete']);
            $pro->setDomaineActivite($data['domaineActivite']);
            $pro->setEmail($data['email']);
            $pro->setDescription($data['description'] ?? null);
            $pro->setStatut($data['statut']);
            $pro->setIsVisible($data['statut'] === Professional::STATUT_ACTIF);
            $pro->setEmailVerifiedAt(new \DateTimeImmutable());
            $pro->setStarsAverage($data['starsAverage']);
            $pro->setTotalAvis($data['totalAvis']);

            if ($type === Professional::TYPE_PHYSIQUE) {
                $pro->setNomResponsable($data['nomResponsable']);
                $pro->setPrenomResponsable($data['prenomResponsable']);
                $pro->setProfession($data['profession']);
                $pro->setSiret($data['siret']);
                $pro->setAdresseRue($data['adresseRue']);
                $pro->setCodePostal($data['codePostal']);
                $pro->setVille($data['ville']);
                $pro->setLatitude($data['latitude'] ?? null);
                $pro->setLongitude($data['longitude'] ?? null);
                $pro->setTelephone($data['telephone']);
                $pro->setGenre($data['genre'] ?? null);
            } else {
                $pro->setSiteEcommerce($data['siteEcommerce'] ?? null);
            }

            $daysAgo = random_int(30, 400);
            $pro->setDateInscription(new \DateTimeImmutable("-{$daysAgo} days"));
            $pro->setCreatedAt(new \DateTimeImmutable("-{$daysAgo} days"));
            $pro->setUpdatedAt(new \DateTimeImmutable('-' . random_int(1, $daysAgo) . ' days'));

            $manager->persist($pro);
            $professionalRefs[$index] = $pro;
        }

        $manager->flush();

        foreach ($this->reviewsData as $reviewData) {
            [$proIndex, $auteur, $note, $commentaire] = $reviewData;

            if (!isset($professionalRefs[$proIndex])) {
                continue;
            }

            $review = new Review();
            $review->setProfessional($professionalRefs[$proIndex]);
            $review->setAuteur($auteur);
            $review->setNote($note);
            $review->setCommentaire($commentaire);
            $review->setIsApproved(true);
            $review->setCreatedAt(new \DateTimeImmutable('-' . random_int(1, 180) . ' days'));

            $manager->persist($review);
        }

        $manager->flush();
    }
}
